#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shoppingMall?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: shop
#    password: 85947ads
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  sql:
#    init:
#      mode: always
#
#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/authservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 9f8ac09ef0137c73ee8b6d722d85c8ee56359b2e9a08976193dcd7aca5b6a91b

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # 발급 받은 client-id #
            client-secret: # 발급 받은 client-secret #
            scope: # 필요한 권한 #
          kakao:
            client-id: # 발급 받은 client-id #
            client-secret: # 발급 받은 client-secret #
            scope: # 필요한 권한 #
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
