#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shoppingMall?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: shop
#    password: 85947ads
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
# DataBase Settings
spring:
  datasource:
    url: jdbc:h2:file:/Users/mun/Downloads/h2/bin/testShoppingMall;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa # edit : 24.02.25
    password: 1234 # edit : 24.02.25

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 568062935487-05ntvs5080cdp9nn6j93hp08ok5d5p17.apps.googleusercontent.com
            client-secret: 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
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email

          naver:
            client-id: l1prMZMzDmHKeGT5TZnn
            client-secret: UXzdODvDU_
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#              scope:
#                - name
#                - email
#                - profile_image
            client-name: Naver

          kakao:
            client-id: 5dcd74bd62cdff4cc4855555d09b0729
            client-secret: Ranl4TGCBAOItYCg3gDC4lLipmG90S1e
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
            #  - account_email 권한이 없어서 못 받았음.
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 1000 # 1000으로 증가

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  sql:
    init:
      mode: always

# jwt.secret.key 값은 256 비트 이상이어야 함. feat : 24.02.25
jwt:
  secret:
    key: 856AE3855C1758616AAAB5B7E4AC2

# hibernate logging
logging:
  level:
    org.hibernate: info

springdoc:
  swagger-ui:
    path: /api-docs.html
    tagsSorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

file:
  dir: /Users/sangmin8817/Desktop/images/